language: python

python:
- '2.7'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - swig3.0
    - g++-4.8

before_install:
- export CXX="g++-4.8" CC="gcc-4.8"
- pip install -r requirements.txt

install:
- pip install -e .

script:
- nosetests
